import type { Metadata } from "next";
import { MyRuntimeProvider } from "@/app/MyRuntimeProvider";
import { AppAuthProvider } from "@/components/auth/app-auth-provider";
import { TooltipProvider } from "@/components/ui/tooltip";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-dvh">
      <body className="h-dvh font-sans">
        <AppAuthProvider>
          <TooltipProvider>
            <MyRuntimeProvider>{children}</MyRuntimeProvider>
          </TooltipProvider>
        </AppAuthProvider>
      </body>
    </html>
  );
}
